# Generated by Django 4.0.5 on 2022-06-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='fcode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='hcode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='styles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
